version: '3.3'

services:
  redis-master:
    #image: 'bitnami/redis:latest'
    image: 'bitnami/redis:5.0.6'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
      # 백업 방식을 선택하는  AOF(Append only File)값, RDB(통째로 dump)
      - REDIS_AOF_ENABLED=yes
      #- master와 slave간 통신에 ssl 암호화를 적용할지 유무값
      #- REDIS_TLS_ENABLED=yes
      #- REDIS_TLS_CERT_FILE=/opt/bitnami/redis/certs/redis.crt
      #- REDIS_TLS_KEY_FILE=/opt/bitnami/redis/certs/redis.key
      #- REDIS_TLS_CA_FILE=/opt/bitnami/redis/certs/redisCA.crt
    #volumes:
      # redis 설정 파일을 커스텀 해서 쓸 경우 마운팅
      #- /path/to/your_redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      # redis 내부의 데이터를 외부로 빼서 영구적으로 보존해야 할 경우
      #- /path/to/redis-persistence:/bitnami/redis/data
    networks:
      - app-tier
    ports:
      - 0.0.0.0:6379:6379

  redis-slave:
    image: 'bitnami/redis:5.0.6'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
      - REDIS_REPLICA_PORT=6379
      - REDIS_AOF_ENABLED=yes
    ports:
      - 6379
    deploy:
      replicas: 2
    depends_on:
      - redis-master
    networks:
      - app-tier

#  redis-sentinel:
#    image: 'bitnami/redis-sentinel:5.0.6'
##    deploy:
##      mode: replicated
##      replicas: 3
#    environment:
#      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
#      - REDIS_MASTER_HOST=redis-master
#      - REDIS_MASTER_PORT_NUMBER=6379
#      - REDIS_MASTER_SET=redis-sentinel-for-test
#      - REDIS_SENTINEL_QUORUM=1
#    depends_on:
#      - redis-master
#      - redis-slave
#    ports:
#      - '26379-26381:26379'
#    #volumes:
#    #  - ./sentinel.conf:/opt/bitnami/redis-sentinel/etc/sentinel.conf
#    networks:
#      - app-tier

networks:
  app-tier:
    driver: bridge

